name: Server Tests (Python)
on:
  push:
    branches:
      - main
      - fix-ci
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
    paths:
      - 'custom-payment-flow/server/python/**'
      - 'prebuilt-checkout-page/server/python/**'
      - 'payment-element/server/python/**'
      - '!**.md'

jobs:
  server_test:
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - server_type: python
            server_image: python:latest
          - server_type: python
            server_image: python:3.8
    uses: ./.github/workflows/wf_server_test.yaml
    secrets: inherit
    with:
      server_type: ${{ matrix.runtime.server_type }}
      server_image: ${{ matrix.runtime.server_image }}
